import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // User Guides Sidebar (Primary)
  guidesSidebar: [
    {
      type: 'doc',
      id: 'guides/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'guides/getting-started/installation',
        'guides/getting-started/your-first-worktree',
        'guides/getting-started/interface-overview',
      ],
    },
    {
      type: 'category',
      label: 'Core Workflows',
      items: [
        'guides/core-workflows/using-treq-with-git-repo',
        'guides/core-workflows/creating-terminal-sessions',
        'guides/core-workflows/executing-implementation-plans',
        'guides/core-workflows/staging-and-committing',
        'guides/core-workflows/code-review-workflow',
        'guides/core-workflows/merging-worktrees',
      ],
    },
    {
      type: 'category',
      label: 'Common Tasks',
      items: [
        'guides/common-tasks/creating-worktrees',
        'guides/common-tasks/pushing-to-remote',
        'guides/common-tasks/discarding-changes',
        'guides/common-tasks/moving-files-between-worktrees',
      ],
    },
    {
      type: 'category',
      label: 'Tips & Tricks',
      items: [
        'guides/tips-and-tricks/customizing-settings',
      ],
    },
  ],

  // Technical Documentation Sidebar
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },
    'keyboard-shortcuts',
    'troubleshooting',
  ],
};

export default sidebars;
