import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "./ui/dialog";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { useToast } from "./ui/toast";
import { 
  gitCreateWorktree, 
  addWorktreeToDb, 
  getRepoSetting, 
  gitExecutePostCreateCommand
} from "../lib/api";

interface CreateWorktreeDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  repoPath: string;
  onSuccess: () => void;
}

export const CreateWorktreeDialog: React.FC<CreateWorktreeDialogProps> = ({
  open,
  onOpenChange,
  repoPath,
  onSuccess,
}) => {
  const [branchName, setBranchName] = useState("");
  const [newBranch, setNewBranch] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const { addToast } = useToast();

  // Helper function to sanitize branch name for display
  const sanitizeBranchForDisplay = (branch: string): string => {
    return branch
      .replace(/\//g, "-")
      .replace(/\\/g, "-")
      .replace(/[*?<>|":]/g, "_")
      .trim();
  };

  // Get auto-generated path for display
  const getAutoGeneratedPath = (): string => {
    if (!branchName.trim()) return `${repoPath}/.treq/worktrees/branch-name`;
    return `${repoPath}/.treq/worktrees/${sanitizeBranchForDisplay(branchName)}`;
  };

  const handleCreate = async () => {
    if (!branchName.trim()) {
      setError("Branch name is required");
      return;
    }

    setLoading(true);
    setError("");

    try {
      // Create the worktree (auto-generates path)
      const worktreePath = await gitCreateWorktree(repoPath, branchName, newBranch);

      // Add to database
      await addWorktreeToDb(repoPath, worktreePath, branchName);

      // Get and execute post-create command if configured
      const postCreateCmd = await getRepoSetting(repoPath, "post_create_command");
      if (postCreateCmd && postCreateCmd.trim()) {
        try {
          addToast({
            title: "Running post-create command...",
            description: "Executing setup command in worktree",
            type: "info",
          });

          const output = await gitExecutePostCreateCommand(worktreePath, postCreateCmd);
          console.log("Post-create command output:", output);
          
          addToast({
            title: "Worktree created successfully",
            description: "Post-create command executed successfully",
            type: "success",
          });
        } catch (cmdError) {
          console.error("Post-create command failed:", cmdError);
          addToast({
            title: "Worktree created",
            description: `Post-create command failed: ${cmdError}`,
            type: "warning",
          });
        }
      } else {
        addToast({
          title: "Worktree created successfully",
          description: `Created worktree for branch ${branchName}`,
          type: "success",
        });
      }

      // Reset form
      setBranchName("");
      setNewBranch(false);
      
      onSuccess();
      onOpenChange(false);
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      setError(errorMsg);
      addToast({
        title: "Failed to create worktree",
        description: errorMsg,
        type: "error",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Create New Worktree</DialogTitle>
          <DialogDescription>
            Create a new git worktree for parallel development
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="branch">Branch Name</Label>
            <Input
              id="branch"
              value={branchName}
              onChange={(e) => setBranchName(e.target.value)}
              placeholder="feature/new-feature"
            />
          </div>

          <div className="flex items-center gap-2">
            <input
              type="checkbox"
              id="newBranch"
              checked={newBranch}
              onChange={(e) => setNewBranch(e.target.checked)}
              className="rounded-sm w-4 h-4 border-input text-primary focus:ring-2 focus:ring-ring focus:ring-offset-1"
            />
            <Label htmlFor="newBranch">Create new branch</Label>
          </div>

          <div className="grid gap-2">
            <Label>Worktree Path (auto-generated)</Label>
            <div className="bg-secondary p-3 rounded-md text-sm font-mono break-all">
              {getAutoGeneratedPath()}
            </div>
            <p className="text-xs text-muted-foreground">
              Worktrees are automatically stored in the repository's .treq/worktrees directory
            </p>
          </div>

          {error && (
            <div className="text-sm text-destructive">
              {error}
            </div>
          )}
        </div>

        <div className="flex justify-end gap-2">
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={loading}
          >
            Cancel
          </Button>
          <Button onClick={handleCreate} disabled={loading}>
            {loading ? "Creating..." : "Create Worktree"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};

