name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        job: ["cargo fmt --check", "cargo test --no-fail-fast"]
        exclude:
          - os: macos-latest
            command: cargo fmt --check

    name: ${{ matrix.command }}
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: ${{ matrix.components }}

      - uses: Swatinem/rust-cache@v2
        if: matrix.job == 'cargo test --no-fail-fast'
        with:
          cache-on-failure: true
          workspaces: "./src-tauri -> target"

      - name: Run command
        working-directory: src-tauri
        run: ${{ matrix.command }}
