name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - job: fmt
            components: rustfmt
            command: cargo fmt --check
          - job: test
            command: cargo test --no-fail-fast
    name: ${{ matrix.job }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: ${{ matrix.components }}

      - uses: Swatinem/rust-cache@v2
        if: matrix.job == 'test'
        with:
          cache-on-failure: true
          workspaces: "./src-tauri -> target"

      - name: ${{ matrix.job }}
        working-directory: src-tauri
        run: ${{ matrix.command }}
